/************************************************************\
 **  Copyright (c) 2011-2017 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/rgwan/riscv/urv-core/td/urv/al_ip/mem_lo.v
 ** Date	:	2017 03 05
 ** TD version	:	3.1.131
\************************************************************/

`timescale 1ns / 1ps

module mem_lo ( doa, dia, addra, cea, ocea, clka, wea, rsta );

	output [7:0] doa;

	input  [7:0] dia;
	input  [9:0] addra;
	input  cea;
	input  ocea;
	input  clka;
	input  wea;
	input  rsta;




	AL_LOGIC_BRAM #( .DATA_WIDTH_A(8),
				.ADDR_WIDTH_A(10),
				.DATA_DEPTH_A(1024),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K(FAST)"),
				.DEBUGGABLE("YES"),
				.FORCE_KEEP("ON"),
				.INIT_FILE("lo.mif"))
			inst(
				.dia(dia),
				.dib({8{1'b0}}),
				.addra(addra),
				.addrb({10{1'b0}}),
				.cea(cea),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(wea),
				.web(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule

module mem_ml ( doa, dia, addra, cea, ocea, clka, wea, rsta );

	output [7:0] doa;

	input  [7:0] dia;
	input  [9:0] addra;
	input  cea;
	input  ocea;
	input  clka;
	input  wea;
	input  rsta;




	AL_LOGIC_BRAM #( .DATA_WIDTH_A(8),
				.ADDR_WIDTH_A(10),
				.DATA_DEPTH_A(1024),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K(FAST)"),
				.DEBUGGABLE("YES"),
				.FORCE_KEEP("ON"),
				.INIT_FILE("ml.mif"))
			inst(
				.dia(dia),
				.dib({8{1'b0}}),
				.addra(addra),
				.addrb({10{1'b0}}),
				.cea(cea),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(wea),
				.web(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule

module mem_mh ( doa, dia, addra, cea, ocea, clka, wea, rsta );

	output [7:0] doa;

	input  [7:0] dia;
	input  [9:0] addra;
	input  cea;
	input  ocea;
	input  clka;
	input  wea;
	input  rsta;




	AL_LOGIC_BRAM #( .DATA_WIDTH_A(8),
				.ADDR_WIDTH_A(10),
				.DATA_DEPTH_A(1024),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K(FAST)"),
				.DEBUGGABLE("YES"),
				.FORCE_KEEP("ON"),
				.INIT_FILE("mh.mif"))
			inst(
				.dia(dia),
				.dib({8{1'b0}}),
				.addra(addra),
				.addrb({10{1'b0}}),
				.cea(cea),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(wea),
				.web(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule

module mem_hi ( doa, dia, addra, cea, ocea, clka, wea, rsta );

	output [7:0] doa;

	input  [7:0] dia;
	input  [9:0] addra;
	input  cea;
	input  ocea;
	input  clka;
	input  wea;
	input  rsta;




	AL_LOGIC_BRAM #( .DATA_WIDTH_A(8),
				.ADDR_WIDTH_A(10),
				.DATA_DEPTH_A(1024),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K(FAST)"),
				.DEBUGGABLE("YES"),
				.FORCE_KEEP("ON"),
				.INIT_FILE("hi.mif"))
			inst(
				.dia(dia),
				.dib({8{1'b0}}),
				.addra(addra),
				.addrb({10{1'b0}}),
				.cea(cea),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(wea),
				.web(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule