/************************************************************\
 **  Copyright (c) 2011-2017 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/rgwan/riscv/urv-core/td/urv/al_ip/regfile_dp_m.v
 ** Date	:	2017 03 05
 ** TD version	:	3.1.131
\************************************************************/

`timescale 1ns / 1ps

module regfile_dp_m ( di, waddr, we, wclk, do, raddr );

	parameter DATA_WIDTH_W = 32; 
	parameter ADDR_WIDTH_W = 5;
	parameter DATA_DEPTH_W = 32;
	parameter DATA_WIDTH_R = 32;
	parameter ADDR_WIDTH_R = 5;
	parameter DATA_DEPTH_R = 32;

	input  [DATA_WIDTH_W-1:0] di;
	input  [ADDR_WIDTH_W-1:0] waddr;
	input  [ADDR_WIDTH_R-1:0] raddr;
	input  wclk,we;

	output [DATA_WIDTH_R-1:0] do;



	AL_LOGIC_DRAM #(
 			.INIT_FILE("NONE"),
			.DATA_WIDTH_W(DATA_WIDTH_W),
			.ADDR_WIDTH_W(ADDR_WIDTH_W),
			.DATA_DEPTH_W(DATA_DEPTH_W),
			.DATA_WIDTH_R(DATA_WIDTH_R),
			.ADDR_WIDTH_R(ADDR_WIDTH_R),
			.DATA_DEPTH_R(DATA_DEPTH_R))
		dram(
			.di(di),
			.waddr(waddr),
			.wclk(wclk),
			.we(we),
			.do(do),
			.raddr(raddr));

endmodule