# ## Log	:	This file is generated by Anlogic Timing Wizard.
# ## File	:	/home/rgwan/riscv/urv-core/td/urv/urv.sdc
# ## Date	:	05 03 2017

#Created Clock
create_clock -name clk -period 10 [get_ports clk_i]

